// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpkecoyqmpsidaqnlkrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwa2Vjb3lxbXBzaWRhcW5sa3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDIwMTgsImV4cCI6MjA3NDI3ODAxOH0.jku02r9mKSsitsgg5U9cOXbc9MD8o9oEz4Swf1TC2rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});